resolver: lts-14.12

# For compatibility with Pandoc ≤ 1.17 (pandoc-types 1.16) which is shipped with
# Debian 9 use lts-7.24!
#
# N.B., building with stack on Debian 9 fails unless
# `~/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/settings` contains the
# following settings:
# 
#     ("C compiler flags", " -fno-PIE -fno-stack-protector"),
#     ("C compiler link flags", " -no-pie"),
#     ("ld flags", " -no-pie"),
# 
# See <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844598>.
